import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { ThemeProvider } from 'next-themes';
import Provider from './providers/Provider';
import { Toaster } from './components/ui/sonner';
import { UserProvider } from './hooks/UserContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'  suppressHydrationWarning={true}>
      <body
        className={`${GeistSans.variable} relative font-sans min-h-screen  bg-[#0B0A0E] dark:text-white antialiased`}
      >
        <svg
          className='pointer-events-none fixed isolate -z-10 opacity-70 mix-blend-soft-light w-full h-full'
          xmlns='http://www.w3.org/2000/svg'
        >
          <filter id='grainy-effect'>
            <feTurbulence
              type='fractalNoise'
              baseFrequency='0.7'
              numOctaves='4'
              stitchTiles='stitch'
            ></feTurbulence>
          </filter>
          <rect width='100%' height='100%' filter='url(#grainy-effect)'></rect>
        </svg>
        <main>
          <UserProvider>
            <Provider>{children}</Provider>
          </UserProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
